config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :update] do
    resources :meetings, only: [:index, :new, :create, :edit, :update]
  end
  get '/users/:user_id/meetings/preview', to: 'meetings#preview', as: :preview_meeting

  get '/meetings/:id/accept', to: 'meetings#accept', as: :accept_meeting
  get '/meetings/:id/decline', to: 'meetings#decline', as: :decline_meeting
  get '/meetings/:id/cancel', to: 'meetings#cancel', as: :cancel_meeting
  get '/meetings/:id/pending', to: 'meetings#pending', as: :pending_meeting

  get '/mymeetings', to: 'meetings#index', as: :my_meetings
  get '/profile/personal', to: 'user_characteristics#edit_personal'
  patch '/profile/personal', to: 'user_characteristics#update_personal'

  get '/profile/professional', to: 'user_characteristics#edit_professional'
  patch '/profile/professional', to: 'user_characteristics#update_professional'

  get '/profile/meeting_availability', to: 'user_characteristics#edit_meeting_availability'
  patch '/profile/meeting_availability', to: 'user_characteristics#update_meeting_availability'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  # belongs_to :user
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:edit, :update]
  before_action :find_meeting, only: [:accept, :decline, :cancel, :pending]
  def index
    @mymeetings = Meeting.where(sender_id: current_user.id).or(Meeting.where(recipient_id: current_user.id))
    @pending_meetings = @mymeetings.where(status: "pending").where("meeting_date_time > :time", time: Time.now.beginning_of_day)
    @past_meetings = @mymeetings.where(status: "accepted").where("meeting_date_time < :time", time: Time.now.beginning_of_day)
    @accepted_meetings = @mymeetings.where(status: "accepted").where("meeting_date_time > :time", time: Time.now.beginning_of_day)
  end

  def new
    @meeting = Meeting.new
    @user = User.find(params[:user_id])
    @relevant_times = @user.availabilities.map(&:available_time_periods).flatten
    @relevant_dates = @user.availabilities.map(&:available_days).flatten
  end

  def preview
    @user = User.find(params[:user_id])
    @current_user = current_user
    # Here we will send some data to a js view to render the preview
  end

  def accept
    @meeting.status = "accepted"
    @meeting.save
    redirect_to my_meetings_path
  end

  def decline
    @meeting.status = "declined"
    @meeting.save
    redirect_to my_meetings_path
  end

  def cancel
    @meeting.status = "cancelled"
    @meeting.save
    redirect_to my_meetings_path
  end

  def pending
    @meeting.status = "pending"
    @meeting.save
    redirect_to my_meetings_path
  end

  def create
    @meeting = Meeting.new
    @meeting.meeting_location = params[:meeting_location]
    @meeting.topic = params[:topic]
    @meeting.status = "pending"
    @recipient = User.find(params[:user_id])
    @currentuser = User.find(current_user.id)
    @meeting.sender_id = @currentuser.id
    @meeting.recipient_id = @recipient.id
    string_to_date_time
    date_time_to_string
    @meeting.meeting_date_time = @new_string.to_s
    selected_activity
    @meeting.suggested_activity = @selected_activity
    # @meeting.save
    if @meeting.save
      redirect_to pending_meeting_path(@meeting), notice: "Congrats. You have sent a meeting request."
    else
      render :new
    end
  end

  def string_to_date_time
    new_string = params[:radrelevant_dates] + " " + params[:radrelevant_times]
    @new_date = new_string.to_datetime
  end

  def date_time_to_string
    @new_string = @new_date.strftime("%A, %e %B at%l:%M %p")
  end

  def selected_activity
    @selected_activity = params[:radrelevant_activities]
  end

  def edit
  end

  def update
    @meeting.update(meeting_params)
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:user_id])
    # redirect_to my_meetings_path
    # flash[:notice] = "Meeting request successfully sent."
  end

  def find_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:meeting_date_time, :suggested_activity, :recipient_id, :meeting_location, :topic)
  end
end

app/views/meetings/_accepted_request_card.html.erb
<% sender = User.find(meeting.sender_id) %>
<% receiver = User.find(meeting.recipient_id) %>

<% if current_user.id == meeting.sender_id %>
  <div class="card-meetings">

    <%= link_to user_path(receiver), :action => 'go' do %>
      <div class="meeting-name">
        <%= receiver.first_name.partition(" ").first %> <%= receiver.last_name[0,1] %>.
      </div>
    <% end %>
    <!-- Career Position -->
    <% if receiver.career_positions.any? %>
      <div class="meeting-title"> <%= receiver.current_title.name %> </div>
      <div class="meeting-company"> @<%= receiver.current_company.name %> </div>
    <% end %>

    <%= link_to user_path(receiver), :action => 'go' do %>
      <div>
        <img src="<%= receiver.photo %>" class="avatar-bordered-meeting-preview" />
      </div>
    <% end  %>

    <div class="meeting-message">
      <em>You would like to <%= meeting.suggested_activity %> with <%= receiver.first_name.partition(" ").first %> <%= receiver.last_name[0,1] %>. at <%= meeting.meeting_location %> on <%= meeting.meeting_date_time.try(:strftime, "%A, %e %B at%l:%M %p")  %>. You would like to talk about <%= meeting.topic %>.</em>
    </div>
    <div class="meeting-status">
      <div class="accepted">
        Accepted
      </div>
    </div>
    <!-- Sent or Received -->
    <div class="meeting-responsibility">
      <%= image_tag 'https://res.cloudinary.com/giugoe/image/upload/v1552435485/Icon_out.png', class: "responsibility-icon" %>
    </div>
    <div class="mail-user">
      <%= mail_to receiver.email do %>
        <i class='far fa-envelope'></i>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="card-meetings">
    <%= link_to user_path(sender), :action => 'go' do %>
    <div class="meeting-name">
      <%= sender.first_name.partition(" ").first %> <%= sender.last_name[0,1] %>.
    </div>
    <% end %>
    <!-- Career Position -->
    <% if sender.career_positions.any? %>
      <div class="meeting-title"> <%= sender.current_title.name %> </div>
      <div class="meeting-company"> @<%= sender.current_company.name %> </div>
    <% end %>

    <%= link_to user_path(sender), :action => 'go' do %>
      <div>
        <img src="<%= sender.photo %>" class="avatar-bordered-meeting-preview" />
      </div>
    <% end %>

    <div class="meeting-message">
      <em>Hey <%= receiver.first_name.partition(" ").first %>! Would you like to <%= meeting.suggested_activity %> with me at <%= meeting.meeting_location %> on <%= meeting.meeting_date_time.try(:strftime, "%A, %e %B at%l:%M %p")  %>? I would like to talk about <%= meeting.topic %> with you.</em>
    </div>
    <div class="meeting-status">
      <div class="accepted">
        Accepted
      </div>
    </div>
    <!-- Sent or Received -->
    <div class="meeting-responsibility">
      <%= image_tag 'https://res.cloudinary.com/giugoe/image/upload/v1552435485/Icon_in.png', class: "responsibility-icon" %>
    </div>
    <div class="mail-user">
      <%= mail_to sender.email do %>
        <i class='far fa-envelope'></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/meetings/_form.html.erb
<div class="request-meeting">
  <div class="request-welcome">
    <h3>Let's meet <%= @user.first_name.partition(" ").first %> <%= @user.last_name[0,1] %>.
    <%= image_tag @user.photo, class: "avatar-bordered-show" %></h3>
  </div>
  <div class="request-form">
    <%= simple_form_for ([@user, @meeting]) do |f|%>
      <div class="request-margin request-meeting-time">
        <h3 class="request-meeting-heading">When?</h3>
        <p>Select a day</p>
        <ul>
          <% @relevant_dates.each do |day| %>
            <li class="request-meeting-option request-meeting-option--date">

              <input type="radio" value="<%= day %>" name="radrelevant_dates" id="relevant_dates_<%= day %>" />
               <label for="relevant_dates_<%= day %>"><%= day.strftime("%a, %d %b") %></label>
            </li>
          <% end %>
        </ul>
        <p>Pick a time</p>
        <ul>
          <% @relevant_times.each do |time| %>
            <li class="request-meeting-option request-meeting-option--time">
              <input name="radrelevant_times" value="<%= time %>" type="radio" id="relevant_times_<%= time %>">
              <label for="relevant_times_<%= time %>"><%= time %></label>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="request-margin request-meeting-location">
        <h3 class="request-meeting-heading">Where?</h3>
        <ul>
          <li class="request-meeting-option request-meeting-option--location">
            <input name="meeting_location" value="<%= "near your address" %>" type="radio" id="meeting_location_yours">
              <label for="meeting_location_yours">
                <%= "#{@user.first_name.partition(" ").first}'s address" %>
              </label>
          </li>
          <li class="request-meeting-option request-meeting-option--location">
            <input name="meeting_location" value="<%= "near my address" %>" type="radio" id="meeting_location_mine">
              <label for="meeting_location_mine">
                <%= "#{current_user.first_name.partition(" ").first}'s address" %>
              </label>
          </li>
          <li class="request-meeting-option request-meeting-option--location">
            <input name="meeting_location" value="half way between us" type="radio" id="meeting_location_half_way">
              <label for="meeting_location_half_way">
                In between us
              </label>
          </li>
        </ul>

      <div class="request-margin request-meeting-activity">
        <h3 class="request-meeting-heading">What?</h3>
        <ul>
          <% @user.activities.each do |activity| %>
            <li class="request-meeting-option">
              <input name="radrelevant_activities" value="<%= activity.description %>" id="activity_ <%= activity %>" type="radio">
              <label for="activity_ <%= activity %>"><%= activity.description.capitalize %>  <i class="<%= activity.symbol %>" ></i></label>

            </li>
          <% end %>
        </ul>
      </div>
      <div class="request-margin request-meeting-topic"><h3 class="request-meeting-heading">Why?</h3>
        <%= text_field_tag :topic, params[:topic], placeholder: "I would like to talk about...", :class => "request-meeting-option request-meeting-option--topic", :id => "topic" %>
      </div>
      <div id="preview"></div>
      <div class="request-meeting-button">
        <%= f.submit class: 'btn-orange-request', value: 'Send Request' %>
        <button class="btn request-preview-button"> <%= link_to 'PREVIEW', preview_meeting_path(@user), remote: true  %></button>

          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/meetings/_past_request_card.html.erb
<% sender = User.find(meeting.sender_id) %>
<% receiver = User.find(meeting.recipient_id) %>

<%# if @past_meetings.length > 0 %>
  <%# raise %>
  <% if current_user.id == meeting.sender_id %>
    <div class="card-meetings">

      <%= link_to user_path(receiver), :action => 'go' do %>
        <div class="meeting-name">
          <%= receiver.first_name.partition(" ").first %> <%= receiver.last_name[0,1] %>.
        </div>
      <% end %>
      <!-- Career Position -->
      <% if receiver.career_positions.any? %>
        <div class="meeting-title"> <%= receiver.current_title.name %> </div>
        <div class="meeting-company"> @<%= receiver.current_company.name %> </div>
      <% end %>

      <%= link_to user_path(receiver), :action => 'go' do %>
        <div>
          <img src="<%= receiver.photo %>" class="avatar-bordered-meeting-preview" />
        </div>
      <% end  %>

      <div class="meeting-message-past">
        <p> <strong>WHEN</strong> <%= meeting.meeting_date_time.try(:strftime, "%A, %e %B at%l:%M %p") %> </p>
        <p> <strong>WHAT</strong> <%= meeting.suggested_activity %> </p>
        <p> <strong>WHY</strong> <%= meeting.topic %> </p>
      </div>

      <!-- Sent or Received -->
      <div class="meeting-responsibility-past">
        <i class="far fa-check-square"></i>
      </div>

      <div class="mail-user">
        <%= mail_to receiver.email do %>
          <i class='far fa-envelope'></i>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="card-meetings">
      <%= link_to user_path(sender), :action => 'go' do %>
      <div class="meeting-name">
        <%= sender.first_name.partition(" ").first %> <%= sender.last_name[0,1] %>.
      </div>
      <% end %>
      <!-- Career Position -->
      <% if sender.career_positions.any? %>
        <div class="meeting-title"> <%= sender.current_title.name %> </div>
        <div class="meeting-company"> @<%= sender.current_company.name %> </div>
      <% end %>

      <%= link_to user_path(sender), :action => 'go' do %>
        <div>
          <img src="<%= sender.photo %>" class="avatar-bordered-meeting-preview" />
        </div>
      <% end %>

      <div class="meeting-message-past">
        <p> <strong>WHEN  </strong> <%= meeting.meeting_date_time.try(:strftime, "%A, %e %B at%l:%M %p") %> </p>
        <p> <strong>WHAT  </strong> <%= meeting.suggested_activity %> </p>
        <p> <strong>WHY  </strong> <%= meeting.topic %> </p>
      </div>

      <!-- Sent or Received -->
      <div class="meeting-responsibility-past">
        <i class="far fa-check-square"></i>
      </div>

      <div class="mail-user">
        <%= mail_to sender.email do %>
          <i class='far fa-envelope'></i>
        <% end %>
      </div>
    </div>
  <% end %>
<%# else %>
  <!-- <p> You haven't had any meetings yet. </p> -->
<%# end %>

app/views/meetings/_pending_request_card.html.erb
<% sender = User.find(meeting.sender_id) %>
<% receiver = User.find(meeting.recipient_id) %>


<% if current_user.id == meeting.sender_id %>
  <div class="card-meetings">
    <%= link_to user_path(receiver), :action => 'go' do %>
      <div class="meeting-name">
        <%= receiver.first_name.partition(" ").first %> <%= receiver.last_name[0,1] %>.
      </div>
    <% end %>
    <!-- Career Position -->
    <% if receiver.career_positions.any? %>
      <div class="meeting-title"> <%= receiver.current_title.name %> </div>
      <div class="meeting-company"> @<%= receiver.current_company.name %> </div>
    <% end %>

    <%= link_to user_path(receiver), :action => 'go' do %>
      <div>
        <img src="<%= receiver.photo %>" class="avatar-bordered-meeting-preview" />
      </div>
    <% end %>

    <div class="meeting-message">
      <em>You would like to <%= meeting.suggested_activity %> with <%= receiver.first_name.partition(" ").first %> <%= receiver.last_name[0,1] %>. at <%= meeting.meeting_location %> on <%= meeting.meeting_date_time.try(:strftime, "%A, %e %B at%l:%M %p")  %>. You would like to talk about <%= meeting.topic %>.</em>
    </div>
    <div class="meeting-status">
      <div class="pending">
        Pending
      </div>
    </div>
    <!-- Sent or Received -->
    <div class="meeting-responsibility">
      <%= image_tag 'https://res.cloudinary.com/giugoe/image/upload/v1552435485/Icon_out.png', class: "responsibility-icon" %>
    </div>

    <%= link_to "Cancel", cancel_meeting_path(meeting), id: "cancel", type: "button", class: "btn btn-book-meeting", data: { confirm: "That's sad. You might miss a great networking opportunity." } %>


    <div class="mail-user">
      <%= mail_to receiver.email do %>
        <i class='far fa-envelope'></i>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="card-meetings">
    <%= link_to user_path(sender), :action => 'go' do %>
      <div class="meeting-name">
        <%= sender.first_name.partition(" ").first %> <%= sender.last_name[0,1] %>.
      </div>
    <% end %>
    <!-- Career Position -->
    <% if sender.career_positions.any? %>
      <div class="meeting-title"> <%= sender.current_title.name %> </div>
      <div class="meeting-company"> @<%= sender.current_company.name %> </div>
    <% end %>

    <%= link_to user_path(sender), :action => 'go' do %>
      <div>
        <img src="<%= sender.photo %>" class="avatar-bordered-meeting-preview" />
      </div>
    <% end %>
    <div class="meeting-message">
      <em>Hey <%= receiver.first_name.partition(" ").first %>! Would you like to <%= meeting.suggested_activity %> with me at <%= meeting.meeting_location %> on <%= meeting.meeting_date_time.try(:strftime, "%A, %e %B at%l:%M %p")  %>? I would like to talk about <%= meeting.topic %> with you.</em>
    </div>
    <div class="meeting-status">
      <div class="pending">
        Pending
      </div>
    </div>
    <!-- Sent or Received -->
    <div class="meeting-responsibility">
      <%= image_tag 'https://res.cloudinary.com/giugoe/image/upload/v1552435485/Icon_in.png', class: "responsibility-icon" %>
    </div>
    <%= link_to "Accept", accept_meeting_path(meeting), id: "accept", class: "btn btn-book-meeting", data: { confirm: "That's awesome. You are one step closer having a great networking experience." } %>
    <%= link_to "Decline", decline_meeting_path(meeting), id: "decline", class: "btn btn-book-meeting", data: { confirm: "That's sad. You might miss a great networking opportunity." } %>
    <div class="mail-user">
      <%= mail_to sender.email do %>
        <i class='far fa-envelope'></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/meetings/index.html.erb
<div class="mymeetings">
  <h3 class="header-3">My upcoming meetings </h3>
  <% @pending_meetings.each do |meeting| %>
    <%= render "meetings/pending_request_card", meeting: meeting %>
  <% end %>

  <% @accepted_meetings.each do |meeting| %>
    <%= render "meetings/accepted_request_card", meeting: meeting %>
  <% end %>

  <h3 class="header-3">My past meetings</h3>
  <% if @past_meetings.any? %>
    <% @past_meetings.each do |meeting| %>
      <%= render "meetings/past_request_card", meeting: meeting %>
    <% end %>
  <% else %>
    <div class="no-meetings-message">
      <p> You haven't had any meetings yet. </p>
    </div>
  <% end %>
</div>

app/views/meetings/new.html.erb
<%= render 'form', meeting: @meeting %>

app/views/meetings/preview.js.erb
function updateDOM() {
  const activity = document.querySelector('input[name="radrelevant_activities"]:checked').value;
  const topic = document.getElementById('topic').value;

  const time = document.querySelector('input[name="radrelevant_times"]:checked').value;
  const date = document.querySelector('input[name="radrelevant_dates"]:checked').value;

  const dateObject = new Date(date + 'T' + time);

  const meeting_location = document.querySelector('input[name="meeting_location"]:checked').value;
  console.log(activity, topic, date, time, meeting_location);

  const preview = document.getElementById('preview');
  preview.innerHTML = `
    <div class="preview">
      <div class="preview-sender">
        <%= image_tag current_user.photo, class: "avatar-preview" %>
        <h3><%= current_user.first_name.partition(" ").first %> <%= current_user.last_name[0,1] %>.</h3>
        <% if current_user.career_positions.any? %>
            <div class="meeting-title"> <%= current_user.current_title.name %> </div>
            <div class="meeting-company"> @ <%= current_user.current_company.name %></div>
        <% end %>
      </div>
      <div class="preview-body">
        <% if current_user.career_positions.any? %>
          <h3 class='strong'>
            <div class="meeting-title"> <%= current_user.current_title.name %> </div>
            <div class="meeting-company"> @ <%= current_user.current_company.name %></div>
          </h3>
        <% end %>
        <p>
          Would you like to ${activity} with me ${meeting_location} on ${dateObject.toDateString()} @ ${time}? I would like to talk about ${topic} with you.
        </p>
      </div>
     </div>
  `;
  // here we will target the div with id preview and update its inner HTML with the actual preview
    //<div class="card-user-user">
      //<img src='https://kitt.lewagon.com/placeholder/users/giuliagoe' class="card-user-user avatar-bordered"/>
    //</div>
}

updateDOM();