config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :update] do
    resources :meetings, only: [:index, :new, :create, :edit, :update]
  end
  get '/users/:user_id/meetings/preview', to: 'meetings#preview', as: :preview_meeting

  get '/meetings/:id/accept', to: 'meetings#accept', as: :accept_meeting
  get '/meetings/:id/decline', to: 'meetings#decline', as: :decline_meeting
  get '/meetings/:id/cancel', to: 'meetings#cancel', as: :cancel_meeting
  get '/meetings/:id/pending', to: 'meetings#pending', as: :pending_meeting

  get '/mymeetings', to: 'meetings#index', as: :my_meetings
  get '/profile/personal', to: 'user_characteristics#edit_personal'
  patch '/profile/personal', to: 'user_characteristics#update_personal'

  get '/profile/professional', to: 'user_characteristics#edit_professional'
  patch '/profile/professional', to: 'user_characteristics#update_professional'

  get '/profile/meeting_availability', to: 'user_characteristics#edit_meeting_availability'
  patch '/profile/meeting_availability', to: 'user_characteristics#update_meeting_availability'
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch
  # Include default devise modules. Others available are:
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  #  :confirmable, :lockable and :timeoutable, :trackable
  devise :database_authenticatable, :validatable, :registerable,
         :recoverable, :rememberable,
         :omniauthable, omniauth_providers: %i[linkedin]

  has_many :sent_meetings, class_name: "Meeting", foreign_key: :sender_id
  has_many :received_meetings, class_name: "Meeting", foreign_key: :recipient_id
  has_many :meetings
  has_many :career_positions
  has_many :job_titles, through: :career_positions
  has_many :companies, through: :career_positions
  has_many :activities
  has_many :availabilities
  has_many :professional_interests
  has_many :skills
  validates_length_of :availabilities, maximum: 2
  # accepts_nested_attributes_for :career_positions, :professional_interests, :availabilities, :activities, :skills

  def current_title
    self.career_positions.first.try(:job_title)
  end

  def current_company
    self.career_positions.first.try(:company)
  end

  def current_position
    self.career_positions.first
  end

  # multisearchable against: [ :address, :radius ]
  pg_search_scope :global_search_user_and_user_characteristics,
  against: [:address, :radius],
  associated_against: {
    activities: [:description],
    companies: [:name],
    job_titles: [:name],
    professional_interests: [:name],
    skills: [:name]
  },
  using: {
    tsearch: { prefix: true }
  }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name # assuming the user model has a name
      user.photo = auth.info.picture_url # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.linkedin_data"] && session["devise.linkedin_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def linkedin
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "LinkedIn") if is_navigational_format?
    else
      session["devise.linkedin_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show]
  def index
    @users = User.all
    # Search method (gets triggered when input is made in navbar-search)
    if params[:search].present?
      @users = @users.global_search_user_and_user_characteristics(params[:search])
    end

    # Filtering Methods (get triggered by applying filters, defined in private section for readability)

    filter_for_radius
    filter_for_interest
    # filter_for_address <- was disabled because it creates dependancy when used with radius filter + is only meant for pro users
    filter_for_activity
    filter_for_skill
    filter_for_availability
    # See only users which have an address so that number of map markers corresponds to number of cards below
    @users = @users.where.not(latitude: nil, longitude: nil)
    # Make current user invisible on landing page
    @users = @users.where.not(id: current_user.id)

    # Set markers to display on the map
    @markers = @users.map do |user|
      {
        lng: user.longitude,
        lat: user.latitude,
        user_id: user.id
      }
    end
  end

  def show
  end

  def create
    @user = User.new(user_params)
  end

  private

  # Filtering Methods for readability

  def filter_for_radius
    if params[:radius].present?
      # @users = @users.within(params[:radius].to_i, :units => :kms, origin: [52.154778, 9.9579652])
      @users = @users.near([current_user.latitude, current_user.longitude], params[:radius].to_i, units: :km)
    end
  end

  def filter_for_interest
    if params[:interest].present?
      @users = @users.joins(:professional_interests).where("professional_interests.name ILIKE ?", "%#{params[:interest]}%")
    end
  end

  def filter_for_address
    if params[:address].present?
      @users = @users.where("address ILIKE ?", "%#{params[:address]}")
    end
  end

  def filter_for_activity
    if params[:activity].present?
      @users = @users.joins(:activities).where("activities.description ILIKE ?", "%#{params[:activity]}")
    end
  end

  def filter_for_skill
    if params[:skill].present?
      @users = @users.joins(:skills).where("skills.name ILIKE ?", "%#{params[:skill]}")
    end
  end

  def filter_for_availability
    if params[:availability].present?
      @users = @users.joins(:availabilities).where("availabilities.day_of_week = ?", params[:availability])
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<div class="map-flexbox">
  <div
    id="map"
    style="width: 100%;
    height: 330px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
  </div>

  <div class="centeredbutton">
    <button type="button" class="btn-orange btn-pill" data-toggle="modal" data-target="#myModal">Filters</button>
  </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog filter-modal" >

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Filter nextBuddies by</h4>
      </div>
      <div class="modal-body">
        <label>
          <div> Radius near me (km): </div>
        </label>
        <%= form_tag users_path, method: :get do %>
          <div class="range-slider">
            <%= range_field_tag :radius, params[:radius], in: 1..10, step: 1, class: 'range-slider__range'%>
            <span class="range-slider__value">5</span>
          </div>

          <label class="filter-modal__section">
            <div>Interest</div> <%= text_field_tag :interest, params[:interest], placeholder: "e.g. innovation" %>
          </label>
          <label class="filter-modal__section">

            <div>Activity</div>
              <%= select_tag :activity, '
              <option value="" disabled selected hidden>Select one activity</option>
              <option>Have lunch</option>
              <option>Go swimming</option>
              <option>Go running</option>
              <option>Go jogging</option>
              <option>Have a coffee</option>
              <option>Have a chat</option>
              <option>Drink a Beer</option>
              <option>Walk the dog</option>
            '.html_safe %>

          </label>
          <label class="filter-modal__section">
            <div>Skill</div> <%= text_field_tag :skill, params[:skill], placeholder: "e.g. UX design" %>
          </label>

          <label class="filter-modal_section">
            <div>Availability</div>
              <%= select_tag :availability, '
              <option value="" disabled selected hidden>Select one weekday</option>
              <option>Monday</option>
              <option>Tuesday</option>
              <option>Wednesday</option>
              <option>Thursday</option>
              <option>Friday</option>
            '.html_safe %>
          </label>
          <p><%= submit_tag ("Filter"), class: "btn-orange-filter" %></p>
        <% end  %>
      </div>
    </div>

  </div>
</div>

<div class="scrolling-wrapper" id="card-scroller">

  <% if @users.empty? %>
    <div class="no-users-search-error">
      <p>Your search criteria didn't render any results.</p>
      <p>Please <strong>redefine</strong> your search!</p>
    </div>
  <% else %>
    <% @users.each do |user| %>
      <%= link_to user_path(user) do %>
        <div class="card-user js-card-user" data-user-id="<%= user.id %>">
          <div class="card-user-inner">
            <div class="card-user-name">
              <h2>
                <%= user.first_name.partition(" ").first %>
                <%= user.last_name[0] %>.
              </h2>
            </div>

            <div class="card-user-location">
                <p><i class="fas fa-map-marker-alt"></i>    <%= user.address %></p>
            </div>

            <div class="card-user-career">
              <p><strong><%= user.current_title.name %> @<%= user.current_company.name %></strong></p>
            </div>

            <div class="user-professional-interests">
              <% user.professional_interests.each do |interest| %>
                <p>#<%= interest.name %></p>
              <% end %>
            </div>

            <div class="card-user-user">
              <%= image_tag user.photo, class: "card-user-user avatar-bordered" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="card-user-show">
  <div class="card-user-show-header">
    <div class="name">
      <h2><%= @user.first_name.partition(" ").first %> <%= @user.last_name[0,1] %>.</h2>
      <div class="career-position">
        <% @user.career_positions.each do |career| %>
          <h5><%= career.job_title.name %>
            <br>
            @<%= career.company.name %> </h5>
        <% end %>
  </div>
    </div>

    <div class="photo">
      <%= image_tag @user.photo, class: "avatar" %>
    </div>
  </div>

  <div class="card-user-show-section">
    <h6>Professional Interests</h6>
    <% @user.professional_interests.each do |interest| %>
      <p>#<%= interest.name %></p>
    <% end %>
  </div>

  <div class="card-user-show-section">
    <h6>Skills</h6>
    <% @user.skills.each do |skill| %>
      <p>
        <%= skill.name.capitalize %>
      </p>
    <% end %>
  </div>

  <div class="card-user-show-section">
    <h6>Bio</h6>
    <p class="js-bio-teaser"><%= @user.bio[0, 100] %>... <a href="#showBio" id="showBio">Read more</a></p>
    <p class="js-bio-full hide"><%= @user.bio %></p>
  </div>

  <div class="card-user-show-section">
    <h6>What I like to do</h6>
    <% @user.activities.each do |activity|  %>
     <i class="fas <%= activity.symbol %>" ></i>
    <% end %>
  </div>

  <div class="card-user-show-section">
    <h6>Availabilities</h6>
      <% @user.availabilities.each do |availability| %>
        <p><%= availability.day_of_week %> <%= availability.period_of_day %>s<p>
      <% end %>
  </div>

  <div class="request-meeting-button">
    <%= link_to "MEET ME", new_user_meeting_path(@user, @availability), class: "btn-orange show" %>
  </div>

</div>