config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :update] do
    resources :meetings, only: [:index, :new, :create, :edit, :update]
  end
  get '/users/:user_id/meetings/preview', to: 'meetings#preview', as: :preview_meeting

  get '/meetings/:id/accept', to: 'meetings#accept', as: :accept_meeting
  get '/meetings/:id/decline', to: 'meetings#decline', as: :decline_meeting
  get '/meetings/:id/cancel', to: 'meetings#cancel', as: :cancel_meeting
  get '/meetings/:id/pending', to: 'meetings#pending', as: :pending_meeting

  get '/mymeetings', to: 'meetings#index', as: :my_meetings
  get '/profile/personal', to: 'user_characteristics#edit_personal'
  patch '/profile/personal', to: 'user_characteristics#update_personal'

  get '/profile/professional', to: 'user_characteristics#edit_professional'
  patch '/profile/professional', to: 'user_characteristics#update_professional'

  get '/profile/meeting_availability', to: 'user_characteristics#edit_meeting_availability'
  patch '/profile/meeting_availability', to: 'user_characteristics#update_meeting_availability'
end

app/views/shared/_footer.html.erb
<div class="footer-big">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-12">
        <div class="footer-widget">
          <div class="home-logo">
            <%= image_tag "https://res.cloudinary.com/giugoe/image/upload/v1552261209/NB_logo.png", height: 100 %>
          </div>
        </div>
      </div>

      <div class="col-md-3 col-sm-4">
        <div class="footer-menu footer-menu--1">
          <ul>
            <li><a href="#">Help</a></li>
            <li><a href="#">Connect</a></li>
            <li><a href="#">Find</a></li>
            <li><a href="#">Discover</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">nextBuddy PRO</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="social-media text-center">
  <ul class="social-icons">
    <li>
      <a href="https://www.facebook.com/" target="_blank" class="s-icon"><i class="fab fa-facebook-f"></i></a></li>
    <li>
      <a href="https://www.twitter.com/" target="_blank" class="s-icon"><i class="fab fa-twitter"></i></a></li>
    <li>
      <a href="https://www.youtube.com/" target="_blank" class="s-icon"><i class="fab fa-youtube"></i></a></li>
    <li>
      <a href="https://www.linkedin.com/" target="_blank" class="s-icon"><i class="fab fa-linkedin-in"></i></a></li>
    <li>
      <a href="https://plus.google.com/" target="_blank" class="s-icon"><i class="fab fa-google-plus-square"></i></a></li>
  </ul>
</div>

<div class="mini-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="copyright-text">
          <p>© 2019
            <a href="#">nextBuddy</a>. All rights reserved. Created by
            <a href="#">nextBuddy</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-nextbuddy">
  <div class="navbar-nextbuddy-right hidden-xs hidden-sm">
  <!-- Logo -->
  <%= link_to users_path, class: "navbar-nextbuddy-brand" do %>
    <%= image_tag "https://res.cloudinary.com/giugoe/image/upload/v1552181634/image.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Profile", "#", class: "navbar-wagon-item navbar-nextbuddy-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-nextbuddy-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-nextbuddy-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-nextbuddy-dropdown-menu">

            <li>
            </li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-nextbuddy-item hidden-md hidden-lg">
      <!-- Logo -->
    <div class="navbar-logo">
      <%= link_to users_path, class: "navbar-nextbuddy-brand" do %>
        <%= image_tag "https://res.cloudinary.com/giugoe/image/upload/v1552261209/NB_logo.png", height: 50 %>
      <% end %>
    </div>
     <div class="navbar-search">
      <%= form_tag(users_path, method: "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "e.g. Marketing or Ruby" %>
      <% end %>
      <span class="fa fa-search navbar-search-icon"></span>
    </div>
    <div class="navbar-dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-nextbuddy-dropdown-menu", height: 80 >
        <li>
          <%= link_to profile_personal_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>

  </div>
</div>